import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const devDir = "../../KAI/.obsidian/plugins/Stella-dev";

// The repo manifest is the real plugin (id "stella"). The vault test copy
// gets its own id so both can be installed side by side.
fs.mkdirSync(devDir, { recursive: true });
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
fs.writeFileSync(`${devDir}/manifest.json`, JSON.stringify(
	{ ...manifest, id: "stella-dev", name: "Stella (dev)" }, null, "\t") + "\n");
fs.copyFileSync("styles.css", `${devDir}/styles.css`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${devDir}/main.js`,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}